trigger:
  branches:
    include:
    - main
  paths:
    include:
    - bin
    - functions
    - internal
    - src
    - dbops.ps*
pr: none
jobs:
- job: cut_new_release_branch
  displayName: Agent phase
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    persistCredentials: True
  - task: PowerShell@2
    displayName: Bump up version and cut a release branch
    inputs:
      filePath: .\build\bump_version.ps1
      arguments: .\dbops.psd1
    env:
      GIT_USER_EMAIL: $(gitUserEmail)
      GIT_USERNAME: $(gitUsername)
      MY_ACCESS_TOKEN: $(System.AccessToken)