
DROP TABLE IF EXISTS a
DROP TABLE IF EXISTS b
DROP TABLE IF EXISTS c
DROP TABLE IF EXISTS d
DROP TABLE IF EXISTS e
DROP TABLE IF EXISTS f
DROP TABLE IF EXISTS a
DROP TABLE IF EXISTS b
DROP TABLE IF EXISTS c
DROP TABLE IF EXISTS d
DROP TABLE IF EXISTS testdeploymenthistory
DROP TABLE IF EXISTS SchemaVersions